### ISSUE TITLE
Why does the Kagi Search extension need to be able to block content on any page?

### ISSUE THREAD

**Issue by umarbutler** [kagisearch/chrome_extension_basic#3]
My browser has notified me that Kagi Search has been disabled due to a change in permissions, one of which is the ability to "block content on any page".

**Comment by MightyPork** [comment]
It's listed in the readme, but the description is not adequate at all. It sounds quite fishy. Also just got it in my browser.

**Comment by vprelovac** [comment]
Afaik that is not needed at all, I will let @hughobrien comment on details.

**Comment by Etheryte** [comment]
This should stem from the `declarativeNetRequest` permission, which is [used by `service_worker.js`](https://github.com/kagisearch/chrome_extension_basic/blob/67d61b4a337e958f98eb80c3bf411b3cf69e22eb/service_worker.js#L32).  

I would like to add that the current description from the readme is neither useful nor tenable.

> The Kagi extension only ever works on Kagi.com, see the code for yourself. This permission is unfortunately named.

Chrome extensions can silently push updates at any time so this situation could change without the user ever noticing. Read the code is not a reasonable justification. The only time a user is notified is when permissions change, such as the addition of this one.

**Comment by hughobrien** [comment]
Hey folks, please take a look at the above PR, it should solve this issue.

Agreed that opening the door to silent rule changes would be bad. Sorry for the noise.
