### ISSUE TITLE
Kagi search as new tab page - Can I make a PR to do this? 

### ISSUE THREAD

**Issue by con-dog** [kagisearch/chrome_extension_basic#8]
Very simple, I pay for and use Kagi. I like it, but I also want Kagi search as my "new tab" landing page. 

If I make a simple PR to do this, would it be accepted? Just let me know yes/no.

If not, I'd be happy to make an open source new tab extension that sets kagi as the default new tab page. 

I build tons of extensions.

Papillon

**Comment by vprelovac** [comment]
We have open sourced the extnesion so that people can submit PRs :)

**Comment by con-dog** [comment]
Thanks, have just made my PR - my first ever open source PR

**Comment by PixeLInc** [comment]
commented on the PR associated, #9 

for anyone reading in the future:
unfortunately not allowed to do it this way as per store guidelines
![img](https://github.com/user-attachments/assets/f1626aa0-7dde-4546-ac63-b2ed8b64a37e)
and at that point it becomes non-optional if we force the new tab to go to a markup file or just direct to kagi like other extensions do.
